name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  Warp_Browsers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
      - run: ls
      - name: prepare env
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m unittest tests.test_portable_build -v
          python3 run.py
      - name: upload chrome
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_${{ env.BUILD_NAME }}
          path: build/release/Chrome
          retention-days: 15
      - name: upload chromium
        uses: actions/upload-artifact@v4
        with:
          name: Chromium_${{ env.BUILD_NAME }}
          path: build/release/Chromium
          retention-days: 15
